services:
  - type: web
    name: attendance-system
    env: python
    buildCommand: "./build.sh"
    startCommand: "./entrypoint.sh"
    staticPublishPath: staticfiles
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
       - key: DJANGO_SETTINGS_MODULE
         value: attendance_system.settings
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "*"
      - key: GDAL_LIBRARY_PATH
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
