services:
  - type: web
    name: attendance-system
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn attendance_system.wsgi:application --bind 0.0.0.0:$PORT
    staticPublishPath: staticfiles
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "attendance-system-6a30.onrender.com,localhost,127.0.0.1"
      - key: GDAL_LIBRARY_PATH
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
