services:
  - type: web
    name: attendance-system
    env: python
    buildCommand: "./build.sh"
    startCommand: gunicorn attendance_system.wsgi:application --bind 0.0.0.0:$PORT
    staticPublishPath: staticfiles
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.5"
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "*"
      - key: GDAL_LIBRARY_PATH
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
